package Utils;

import Exceptions.InvalidSyntaxException;
import Main.OperatingSystem;

public class MemoryUtils {
    public static int getMemorySize() {
        return OperatingSystem.Memory.length;
    }

    /**
     * The raw address is the address in the format offset($register)
     * ex.: 4($sp)
     * 
     * @param rawAddress : String - the address in the format offset($register)
     * @return int : the physical address in the memory
     */
    public static int getAddressFromRawAddress(String rawAddress) throws InvalidSyntaxException {
        //This code was autogenerated by the one and only Mr.G :
        try {
            int offset = Integer.parseInt(rawAddress.split("\\(")[0]);
            String register = rawAddress.split("\\(")[1].split("\\)")[0];
            int registerValue = OperatingSystem.registers.get(register);
            return offset + registerValue;
        } catch (Exception e) {
            throw new InvalidSyntaxException("Invalid syntax for the address : " + rawAddress, OperatingSystem.programCounter);
        }
    }
    
}
